spring:
  application:
    name: server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DBMS_IP:localhost}:5432/postgres
    username: loadbalancer
    password: test1234
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
    database: postgresql
server:
  port: ${BACKEND_PORT:8083}
